name: Push to Dune on Commit

on:
  push:
    branches:
      - main
    paths:
      - 'queries/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Log directory structure
        run: |
          pwd
          ls -R

      - name: Install dependencies
        run: uv sync

      - name: Update all queries from Dune, by overwriting queries with repo query text
        env:
          DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
        run: uv run python -u scripts/push_to_dune.py
